### ISSUE TITLE
Redis configuration for karma?

### ISSUE THREAD

**Issue by scofield-ua** [haraka/haraka-plugin-karma#41]
Hello. Is some redis configuration\tuning required before using karma? For example: `timeout`?

The reason I asking is because I noticed some "errors" from karma plugin in logs:
```
[ERROR] [C38A83C6-5BC6-4F60-93A1-7C154097BE82] [karma] karma requires the redis plugin
[ERROR] [C38A83C6-5BC6-4F60-93A1-7C154097BE82.1] [karma] redis_unsubscribe called when no redis
```

**Comment by tmechlinski** [comment]
No need any changes.TomWysłano z mojego urządzenia Galaxy
-------- Oryginalna wiadomość --------Od: Dmitry ***@***.***> Data: 15.02.2022  18:45  (GMT+01:00) Do: haraka/haraka-plugin-karma ***@***.***> DW: Subscribed ***@***.***> Temat: [haraka/haraka-plugin-karma] Redis configuration for karma? (Issue #41) 
Hello. Is some redis configuration\tuning required before using karma? For example: timeout?
The reason I asking is because I noticed some "errors" from karma plugin in logs:
[ERROR] [C38A83C6-5BC6-4F60-93A1-7C154097BE82] [karma] karma requires the redis plugin
[ERROR] [C38A83C6-5BC6-4F60-93A1-7C154097BE82.1] [karma] redis_unsubscribe called when no redis

**Comment by scofield-ua** [comment]
Should I care about those errors then and is there a way how can fix them?

**Comment by tmechlinski** [comment]
Which error You meant?Wysłano z mojego urządzenia Galaxy
-------- Oryginalna wiadomość --------Od: Dmitry ***@***.***> Data: 15.02.2022  19:46  (GMT+01:00) Do: haraka/haraka-plugin-karma ***@***.***> DW: Tomek Mechliński ***@***.***>, Comment ***@***.***> Temat: Re: [haraka/haraka-plugin-karma] Redis configuration for karma? (Issue #41) 
Should I care about those errors then and is there a way how can fix them?

**Comment by scofield-ua** [comment]
From the logs above.

`[ERROR] [C38A83C6-5BC6-4F60-93A1-7C154097BE82] [karma] karma requires the redis plugin`

and

`[ERROR] [C38A83C6-5BC6-4F60-93A1-7C154097BE82.1] [karma] redis_unsubscribe called when no redis`

**Comment by msimerson** [comment]
You need to add the redis plugin in your Haraka `config/plugins` file.
